version: '3.8'

services:
  app:
    container_name: feedbackbot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/app/app"
#    env_file:
#      - ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Africa/Cairo
      - /etc/localtime:/etc/localtime:ro
    command: sh -c "cd app && /app/.venv/bin/python3.12 -m feedbackbot"
